### ISSUE TITLE
Plugin fails to run with Jenkins running jdk11

### ISSUE THREAD

**Issue by dalgibbard** [leapwork/Jenkins-plugin#38]
Hi all,
This plugin doesn't work on Jenkins instances which are running Java11, eg:
```
 docker run -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts-jdk11
```
The error occurs on the Report Generation step:
```
ERROR: Failed to create a report file
ERROR: Implementation of JAXB-API has not been found on module path or classpath.
ERROR: Leapwork for Jenkins plugin finished with errors
ERROR: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
```

Digging through various documentation from Jenkins, eg:
* https://wiki.jenkins-ci.org/display/JENKINS/JAXB-usage-in-Jenkins-plugins.html
* https://issues.jenkins.io/browse/JENKINS-55202

This is caused by the removal of JAXB modules in the base Java installation in Java 9+.

I tried to edit the Jenkins launcher and add -Djavax.xml.bind.JAXBContextFactory=com.sun.xml.bind.v2.ContextFactory in the JAVA_OPTS (as suggested in the first link above) but this didn't work.

The _only_ working fix I have for this is to manually copy the following jars:
* https://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.4.0-b180830.0359/jaxb-api-2.4.0-b180830.0359.jar
* https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-core/3.0.2/jaxb-core-3.0.2.jar
* https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.4.0-b180830.0438/jaxb-impl-2.4.0-b180830.0438.jar
* https://repo1.maven.org/maven2/org/glassfish/jaxb/jaxb-runtime/2.3.0-b170127.1453/jaxb-runtime-2.3.0-b170127.1453.jar

Into ```/var/jenkins_home/war/WEB-INF/lib/``` ... But this seems like a terrible hack. Specifically because it's not forward-maintainable (plugin upgrades could break dependencies), and it also doesn't work well for managed Jenkins Instances (where you don't have access to customise the Jenkins Controller image).

**Comment by BirSikanderMahajan** [comment]
this Issue has been fixed in Plugin version V4.0.6
